# Uncomment the next line to define a global platform for your project
# platform :ios, '1# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :release,
}

# Flutter-specific settings
flutter_root = File.expand_path('..', File.dirname(__FILE__))
load File.join(flutter_root, 'Flutter', 'flutter_export_environment.sh')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
